name: CI/CD
on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is environment where work flow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        run: echo "code cloned from github"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build a cotainer
        run: echo "container build succesfully"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container running or not
        run: echo "container running"
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: the application is working
        run: echo "the application is working "
